Credit Dharma/Controllers/ClientsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Credit_Dharma.Data;
using Credit_Dharma.Models;
using Credit_Dharma.Services.Fihogar;
using Credit_Dharma.Helper;
using System.Text.Json;
using Credit_Dharma.Services;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;

namespace Credit_Dharma.Views
{
    public class ClientsController : Controller
    {
        private readonly Credit_DharmaContext _context;
        public ClientsController(Credit_DharmaContext context)
        {
            
            _context = context;
        }

        // GET: Clients
        public async Task<IActionResult> Index()
        {


         var clientes = await _context.Client.ToListAsync();

            clientes = clientes.FindAll(c => c.AccountSubType.ToUpper().Trim() == "Loan".ToUpper().Trim());
            // Response.WriteAsync(CustomFuctions.GetPaymentCount(DateTime.Parse( clientes.First().OpeningDate),DateTime.Now).ToString());
            var usuariosLista = _context.Usuario.ToList();
            ViewBag.usuarios = usuariosLista;

            if (Session.Loggedin)
            {
              
                foreach (var cliente in clientes)
                {
                    try
                    {
                        cliente.PendingPayments = CustomFuctions.GetPaymentCount(DateTime.Parse(cliente.OpeningDate), DateTime.Now) - cliente.Payments;

                    }
                    catch(ArgumentNullException)
                    {
                        cliente.PendingPayments = 0;
                    }
                    await _context.SaveChangesAsync();
                }
                if (Session.Admin)
                {
                    clientes = clientes.FindAll(c => c.AccountSubType.ToUpper().Trim() == "Loan".ToUpper().Trim());
                    return View(clientes);
                }
                else
                {


                 return View( _context.Client.FromSqlRaw("SELECT * FROM[dbo].[Client] Where[Assigned] = '"+Session.Username+"'"));
                        
                    
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

        }

        // GET: Clients/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (Session.Loggedin)
            {

                var usuariosLista = _context.Usuario.ToList();
                ViewBag.usuarios = usuariosLista;

                if (id == null)
                {
                    return NotFound();
                }

                
                var client = await _context.Client
                    .FirstOrDefaultAsync(m => m.Identification == id);


                if (client == null)
                {
                    return NotFound();
                }

                try
                {
                    ViewData["Montos"] = JsonSerializer.Serialize(new double[] { client.Amount, client.TotalAmount - client.Amount });
                    ViewData["Cuotas"] = JsonSerializer.Serialize(new double[] { client.Payments, client.PendingPayments });
                }
                catch(ArgumentNullException)
                { 
                    ViewData["Montos"] = JsonSerializer.Serialize(new double[] {0});
                    ViewData["Cuotas"] = JsonSerializer.Serialize(new double[] { 0});
                }





                if (client.PendingPayments > 3)
                {
                   
                    ViewData["Morosidad"] = JsonSerializer.Serialize(new double[] {CustomFuctions.GetMorosidad(_context.Client.ToList(),client) });

                    // Response.WriteAsync(JsonSerializer.Serialize(new float[] { morosidad}).ToString());
                }





                else
                {
                    ViewData["Morosidad"] = 0;
                }
                return View(client);
            }
            else
            {
                return RedirectToAction("Index","Home");
            }
        }

        // GET: Clients/Create
        public IActionResult Create()
        {
            if (Session.Admin)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // POST: Clients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Identification,Status,Currency,AccountSubType,Nickname,OpeningDate,Amount,Name,Lastname,Email,PhoneNumber")] Cliente client)
        {
            if (ModelState.IsValid)
            {
                _context.Add(client);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (Session.Admin)
            {
                var usuariosLista = (from Usuario in _context.Usuario
                                   select new SelectListItem()
                                   {
                                       Text = Usuario.Username,
                                       Value = Usuario.Username
                                   }).ToList();




                ViewBag.usuarios = usuariosLista;

                if (id == null)
                {
                    return NotFound();
                }

                var client = await _context.Client.FindAsync(id);
                if (client == null)
                {
                    return NotFound();
                }
                return View(client);
            }

            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Identification,Status,Currency,AccountSubType,Nickname,OpeningDate,Amount,Name,Lastname,Email,PhoneNumber,TotalAmount,Payments,PendingPayments,MonthlyPay,Assigned")] Cliente client)
        {
            if (id != client.Identification)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(client);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientExists(client.Identification))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (Session.Admin)
            {

            
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Client
                .FirstOrDefaultAsync(m => m.Identification == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

            else
            {
                return RedirectToAction("Index", "Home");
            }


        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var client = await _context.Client.FindAsync(id);
            _context.Client.Remove(client);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClientExists(string id)
        {
            return _context.Client.Any(e => e.Identification == id);
        }

        public async Task<ActionResult> RefreshAsync()
        {
            if (Session.Admin)
            {
                await Account.RefreshAccountsAsync(_context, _context.Client);
            }
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> NotifyClientEmail(string id)
        {
            var cliente = await _context.Client.FirstOrDefaultAsync(m => m.Identification == id);

            try
            {
                Email.SendEmail(cliente.Identification, cliente.Email, @"Tiene un total de " + cliente.PendingPayments + " cuotas vencidas, favor pagar lo antes posible.");
                _context.Registro.Add(new Registro() { NotificationDate = DateTime.Now.ToString(), Username = Session.Username, UserAccountNumber = cliente.Identification, NotificationDetails = "Notificacion enviada via correo desde el sistema",FlowStep="Recordatorio Rapido Por Correo" });
                await _context.SaveChangesAsync();
            }
            catch (ArgumentNullException)
            {

                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }


        public ActionResult ExportToCsv()
        {
            List<Cliente> clientes;

            if (Session.Admin)
            {
       

Credit Dharma/Controllers/RegistrosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Credit_Dharma.Data;
using Credit_Dharma.Models;
using Credit_Dharma.Helper;
using System.Text;

namespace Credit_Dharma.Controllers
{
    public class RegistrosController : Controller
    {
        private readonly Credit_DharmaContext _context;

        public RegistrosController(Credit_DharmaContext context)
        {
            _context = context;
        }

        // GET: Registros
        public async Task<IActionResult> Index()
        {
            if(Session.Loggedin)
            { 
            return View(await _context.Registro.ToListAsync());
        }
            else
            {
                return RedirectToAction("Index","Home");
    }
}

        // GET: Registros/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (Session.Loggedin)
            {


                if (id == null)
                {
                    return NotFound();
                }

                var registro = await _context.Registro
                    .FirstOrDefaultAsync(m => m.IdNotification == id);
                if (registro == null)
                {
                    return NotFound();
                }

                return View(registro);
            }
            else
            {
                return RedirectToAction("Index","Home");
            }
        }

        // GET: Registros/Create
        public IActionResult Create()
        {

            if(Session.Loggedin)
            {

                ViewBag.clientes = (from cliente in _context.Client
                                    select new SelectListItem()
                                    {
                                        Text = cliente.Identification,
                                        Value = cliente.Identification
                                    }).ToList();

                return View();
        }
            else
            {
                return RedirectToAction("Index","Home");
    }
}

        // POST: Registros/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdNotification,NotificationDate,UserAccountNumber,NotificationDetails,Username,FlowStep")] Registro registro)
        {
            if (ModelState.IsValid)
            {
                _context.Add(registro);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(registro);
        }

        // GET: Registros/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (false)
            {

            
            if (id == null)
            {
                return NotFound();
            }

            var registro = await _context.Registro.FindAsync(id);
            if (registro == null)
            {
                return NotFound();
            }
            return View(registro);
        }
            else
            {
                return RedirectToAction("Index","Home");
             }
           }

        // POST: Registros/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdNotification,NotificationDate,UserAccountNumber,NotificationDetails,Username")] Registro registro)
        {
            if (id != registro.IdNotification)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(registro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RegistroExists(registro.IdNotification))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(registro);
        }

        // GET: Registros/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (false)
            {
            if (id == null)
            {
                return NotFound();
            }

            var registro = await _context.Registro
                .FirstOrDefaultAsync(m => m.IdNotification == id);
            if (registro == null)
            {
                return NotFound();
            }

            return View(registro);
        }
            else
            {
                return RedirectToAction("Index","Home");
    }
       }

        // POST: Registros/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var registro = await _context.Registro.FindAsync(id);
            _context.Registro.Remove(registro);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RegistroExists(int id)
        {
            return _context.Registro.Any(e => e.IdNotification == id);
        }



        public ActionResult ExportToCsv()
        {
            var registros = _context.Registro.ToList();

            StringBuilder sb = new StringBuilder();
            sb.Append("ID");
            sb.Append(",");
            sb.Append("Fecha");
            sb.Append(",");
            sb.Append("Numero de cuenta");
            sb.Append(",");
            sb.Append("Paso en el flujo");
            sb.Append(",");
            sb.Append("Accion realiazada por ");
            sb.Append(",");
            sb.Append("Detalles");
            sb.AppendLine();
            foreach (var registro in registros)
            {
                sb.Append(registro.IdNotification);
                sb.Append(",");
                sb.Append(registro.NotificationDate);
                sb.Append(",");
                sb.Append(registro.UserAccountNumber);
                sb.Append(",");
                sb.Append(registro.FlowStep);
                sb.Append(",");
                sb.Append(registro.Username);
                sb.Append(",");
                sb.Append(registro.NotificationDetails);
                sb.AppendLine();
            }
            return File(Encoding.ASCII.GetBytes(sb.ToString()), "text/csv", DateTime.Now.Date.ToString("dd-MM-yyyy") + "_Registro_Notificaciones.csv");
        }
    }
}

Credit Dharma/Views/Shared/404.cshtml
<div class="container">

    <section class="section error-404 min-vh-100 d-flex flex-column align-items-center justify-content-center">
        <h1>404</h1>
        <h2>Esta pagina no existe</h2>
        <a class="btn" asp-action="Index">Volver al inicio</a>
        <img src="assets/img/not-found.svg" class="img-fluid py-5" alt="Pagina no encontrada">
    </section>

</div>

Credit Dharma/Views/Shared/_Footer.cshtml
  <!-- ======= Footer ======= -->
<footer id="footer" class="footer">
    <div class="copyright">
        &copy; Copyright <strong><span>@TempData["AppName"]</span></strong><span> @DateTime.Today.Year</span>. All Rights Reserved
    </div>
</footer><!-- End Footer -->

Credit Dharma/Views/Shared/_Header.cshtml
  @using Credit_Dharma.Helper;
    
    <!-- ======= Header ======= -->
<header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
        <a asp-action="Index" asp-controller="Home" class="logo d-flex align-items-center">
           <img src="~/assets/img/dharma-wheel.png" alt="">
            <span class="d-none d-lg-block">@TempData["AppName"]</span>
        </a>
        <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->


    <nav class="header-nav ms-auto">
        <ul class="d-flex align-items-center">


                <li class="nav-item dropdown pe-3">

                    <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
                        <span class="d-none d-md-block dropdown-toggle ps-2">@Session.Username</span>
                    </a><!-- End Profile Iamge Icon -->

                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                        <li class="dropdown-header">
                            @{


                                <h6>@Session.Username</h6>
                                <span>@Session.Role</span>
                            }
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        @{
                            if (Session.Loggedin)
                            {
                                <li>
                                    <a class="dropdown-item d-flex align-items-center" asp-controller="Usuarios" asp-action="Signout">
                                        <i class="bi bi-box-arrow-right"></i>
                                        <span>Cerrar Sesion</span>
                                    </a>
                                </li>
                            }
                            else
                            {
                                <li>
                                    <a class="dropdown-item d-flex align-items-center" asp-controller="Usuarios" asp-action="Login">
                                        <i class="bi bi-box-arrow-in-right"></i>
                                        <span>Iniciar Sesion</span>
                                    </a>
                                </li>
                            }
                        }
                    </ul><!-- End Profile Dropdown Items -->
                </li><!-- End Profile Nav -->
         

</nav><!-- End Icons Navigation -->

</header><!-- End Header -->

Credit Dharma/Views/Shared/_Layout.cshtml
@{
    TempData["AppName"] = "Credit Dharma";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <title>@ViewData["Title"] - @TempData["AppName"]</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/assets/img/dharma-wheel.png" rel="icon">
    <link href="~/assets/img/dharma-wheel.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assets/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="~/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
    <link href="~/assets/vendor/simple-datatables/style.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/assets/css/style.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: NiceAdmin - v2.1.0
    * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->
</head>
<body>

    <partial name="_Header" />
    <partial name="_Sidebar" />
    <main id="main" class="main">

        @RenderBody()
    </main>
    <partial name="_Footer" />
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.js"></script>
    <script src="~/assets/vendor/php-email-form/validate.js"></script>
    <script src="~/assets/vendor/quill/quill.min.js"></script>
    <script src="~/assets/vendor/tinymce/tinymce.min.js"></script>
    <script src="~/assets/vendor/simple-datatables/simple-datatables.js"></script>
    <script src="~/assets/vendor/chart.js/chart.min.js"></script>
    <script src="~/assets/vendor/apexcharts/apexcharts.min.js"></script>
    <script src="~/assets/vendor/echarts/echarts.min.js"></script>

    <link rel="stylesheet" href="~/lib/select2/css/select2.min.css" />
    <script src="~/lib/select2/js/select2.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- Template Main JS File -->
    <script src="~/assets/js/main.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Credit Dharma/Views/Shared/_Sidebar.cshtml
@using Credit_Dharma.Helper; 
 <!-- ======= Sidebar ======= -->
<aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

        <li class="nav-item">
            <a class="nav-link collapsed" asp-controller="Home" asp-action="Index">
                <i class="bi bi-grid"></i>
                <span>Dashboard</span>
            </a>
        </li><!-- End Dashboard Nav -->




        @{

            if (Session.Admin)
            {
                <li class="nav-item">
                    <a class="nav-link collapsed" data-bs-target="#components-nav" data-bs-toggle="collapse" href="#">
                        <i class="ri-user-3-line"></i><span>Usuarios</span><i class="bi bi-chevron-down ms-auto"></i>
                    </a>
                    <ul id="components-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                        <li>
                            <a asp-controller="Usuarios" asp-action="Index">
                                <i class="bi bi-circle"></i><span>Admnistrar Usuarios</span>
                            </a>
                        </li>

                    </ul>
                </li><!-- End Users Nav -->

            }
        }

        @{
            if (!Session.Loggedin)
            {

                <li class="nav-item">
                    <a class="nav-link collapsed" asp-controller="Usuarios" asp-action="Login">
                        <i class="bi bi-box-arrow-in-right"></i>
                        <span>Iniciar Sesion</span>
                    </a>
                </li><!-- End Login Page Nav -->
            }
            else
            {
                <li class="nav-item">
                    <a class="nav-link collapsed" data-bs-target="#forms-nav" data-bs-toggle="collapse" href="#">
                        <i class="bi bi-file-earmark-person"></i><span>Clientes</span><i class="bi bi-chevron-down ms-auto"></i>
                    </a>
                    <ul id="forms-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                        <li>
                            <a asp-controller="Clients" asp-action="Index">
                                <i class="bi bi-circle"></i><span>Consultar Clientes</span>
                            </a>
                        </li>

                    </ul>
                </li><!-- End Clients Nav -->
                <!-- End Registries Nav -->
                <li class="nav-item">
                    <a class="nav-link collapsed" data-bs-target="#tables-nav" data-bs-toggle="collapse" href="#">
                        <i class="bi bi-journal-bookmark"></i><span>Registros de Comunicacion</span><i class="bi bi-chevron-down ms-auto"></i>
                    </a>
                    <ul id="tables-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
                        <li>
                            <a asp-action="Index" asp-controller="Registros">
                                <i class="bi bi-circle"></i><span>Consultar Registos</span>
                            </a>
                        </li>
                    </ul>
                </li><!-- End Registries Nav -->

                <li class="nav-item">
                    <a class="nav-link collapsed" asp-controller="Usuarios" asp-action="Signout">
                        <i class="bi bi-box-arrow-in-right"></i>
                        <span>Cerrar Sesion</span>
                    </a>
                </li>
            }
        }

    </ul>

</aside><!-- End Sidebar-->